# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cbdcbb0c0b25762801ea9b4b221dcd49501ce0a7ae8b542aa081322679f06da6597c6f598c42181747209380a21fb87cee1f2c45bdb0e17d9bb724ee0f35350e

test:
  secret_key_base: 45dd61ebaa06ff82fad4a207787bdf0529765fa2423d085557e50b090032030bea69683852be65d5b043ddc407f07029096c48e989a9b7c1fa5481a366378a20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
